version: '3.8'

services:
  mangrullo:
    build: .
    container_name: mangrullo
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MANGRULLO_LOG_LEVEL=info
      - MANGRULLO_INTERVAL=3600
      - MANGRULLO_ALLOW_MAJOR=false
    networks:
      - mangrullo-network

volumes:
networks:
  mangrullo-network:
    driver: bridge