site_name: Mangrullo Documentation
theme:
  name: material
nav:
    - Home: index.md
    - Design: DESIGN.md
    - Docker: DOCKER.md
    - Update Algorithm: UPDATE_ALGORITHM.md
    - Web UI Design: WEB_UI_DESIGN.md
    - Claude Integration: CLAUDE.md